$c_dir = Get-Location
Set-Location -Path $c_dir/platform-tools


function m5 {
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.mipicks
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.nbu.paisa.user
    .\adb.exe shell pm uninstall --user 0 com.facebook.appmanager
    .\adb.exe shell pm uninstall --user 0 com.facebook.services
    .\adb.exe shell pm uninstall --user 0 com.facebook.system
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.glgm
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.messaging
    .\adb.exe shell pm uninstall --user 0 com.android.hotwordenrollment.okgoogle
    .\adb.exe shell pm uninstall --user 0 com.android.hotwordenrollment.xgoogle
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.googleassistant
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.nbu.files
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.photos
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.safetyhub
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.subscriptions.red
    .\adb.exe shell pm uninstall --user 0 cn.wps.xiaomi.abroad.lite
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.payment
    .\adb.exe shell pm uninstall --user 0 com.google.android.videos
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.account
    .\adb.exe shell pm uninstall --user 0 com.miui.cloudservice
    .\adb.exe shell pm uninstall --user 0 com.android.thememanager
    .\adb.exe shell pm uninstall --user 0 com.miui.miservice
    .\adb.exe shell pm uninstall --user 0 com.miui.yellowpage
    .\adb.exe shell pm uninstall --user 0 com.android.chrome
    .\adb.exe shell pm uninstall --user 0 com.fido.asm
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.wellbeing
    .\adb.exe shell pm uninstall --user 0 com.google.android.projection.gearhead
    .\adb.exe shell pm uninstall --user 0 com.google.android.tts
    .\adb.exe shell pm uninstall --user 0 com.miui.android.fashiongallery
    .\adb.exe shell pm uninstall --user 0 com.milink.service
    .\adb.exe shell pm uninstall --user 0 com.miui.analytics
    .\adb.exe shell pm uninstall --user 0 com.miui.backup
    .\adb.exe shell pm uninstall --user 0 com.miui.bugreport
    .\adb.exe shell pm uninstall --user 0 com.miui.cloudbackup
    .\adb.exe shell pm uninstall --user 0 com.miui.micloudsync
    .\adb.exe shell pm uninstall --user 0 com.miui.player
    .\adb.exe shell pm uninstall --user 0 com.google.android.youtube
    
    
    Set-Location ..
}

function s22 {
    .\adb.exe shell pm uninstall --user 0 com.google.android.projection.gearhead
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.app.appsedge
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.ardrawing
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.aremoji
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.aremojieditor
    .\adb.exe shell pm uninstall --user 0 com.sec.android.mimage.avatarstickers
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.arzone
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.visionintelligence
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.bixby.agent
    .\adb.exe shell pm uninstall --user 0 com.android.chrome
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.themestore
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.game.gametools
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.game.gamehome
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.game.gos
    .\adb.exe shell pm uninstall --user 0 com.google.android.gm
    .\adb.exe shell pm uninstall --user 0 com.google.android.googlequicksearchbox
    .\adb.exe shell pm uninstall --user 0 com.google.hotwordenrollment.xgoogle
    .\adb.exe shell pm uninstall --user 0 com.google.hotwordenrollment.okgoogle
    .\adb.exe shell pm uninstall --user 0 com.google.android.gms.location.history
    .\adb.exe shell pm uninstall --user 0 com.google.android.gms #this might cause some crazy stuff to happen
    .\adb.exe shell pm uninstall --user 0 com.android.vending
    .\adb.exe shell pm uninstall --user 0 com.microsoft.appmanager
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.mdx
    .\adb.exe shell pm uninstall --user 0 com.google.audio.hearing.visualization.accessibility.scribe
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.maps
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.messaging
    .\adb.exe shell pm uninstall --user 0 com.facebook.system
    .\adb.exe shell pm uninstall --user 0 com.facebook.appmanager
    .\adb.exe shell pm uninstall --user 0 com.facebook.services
    .\adb.exe shell pm uninstall --user 0 com.swiftkey.swiftkeyconfigurator
    .\adb.exe shell pm uninstall --user 0 com.touchtype.swiftkey
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.app.routines
    .\adb.exe shell pm uninstall --user 0 com.microsoft.skydrive
    .\adb.exe shell pm uninstall --user 0 com.sec.android.app.billing
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.scloud
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.app.spage
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.mateagent
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.samsungpass
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.ipsgeofence
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.app.taskedge
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.accessibility.voiceaccess
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.bixby.wakeup
    .\adb.exe shell pm uninstall --user 0 com.samsung.android.allshare.service.fileshare
    .\adb.exe shell pm uninstall --user 0 com.google.android.youtube

    Set-Location ..
}

function pad5 {
    
}

function rdmi6 {
    .\adb.exe shell pm uninstall --user 0 com.android.browser
    .\adb.exe shell pm uninstall --user 0 com.android.calendar
    #.\adb.exe shell pm uninstall --user 0 com.android.cellbroadcastreciever
    .\adb.exe shell pm uninstall --user 0 com.android.chrome
    .\adb.exe shell pm uninstall --user 0 com.android.documentsui
    .\adb.exe shell pm uninstall --user 0 com.android.dreams.basic
    .\adb.exe shell pm uninstall --user 0 com.android.dreams.phototable
    .\adb.exe shell pm uninstall --user 0 com.android.egg
    .\adb.exe shell pm uninstall --user 0 com.android.emergency
    .\adb.exe shell pm uninstall --user 0 com.android.printspooler
    .\adb.exe shell pm uninstall --user 0 com.android.providers.calendar
    .\adb.exe shell pm uninstall --user 0 com.android.providers.downloads
    .\adb.exe shell pm uninstall --user 0 com.android.providers.downloads.ui
    .\adb.exe shell pm uninstall --user 0 com.android.thememanager
    .\adb.exe shell pm uninstall --user 0 com.android.updater
    .\adb.exe shell pm uninstall --user 0 com.android.wallpaper.livepicker
    .\adb.exe shell pm uninstall --user 0 com.caf.fmradio
    .\adb.exe shell pm uninstall --user 0 com.facebook.appmanager
    .\adb.exe shell pm uninstall --user 0 com.facebook.services
    .\adb.exe shell pm uninstall --user 0 com.facebook.system
    .\adb.exe shell pm uninstall --user 0 com.fido.asm
    .\adb.exe shell pm uninstall --user 0 com.fido.xiaomi.uafclient
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.classroom
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.docs
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.maps
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.tachyon
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.turbo
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.wellbeing
    .\adb.exe shell pm uninstall --user 0 com.google.android.calendar
    .\adb.exe shell pm uninstall --user 0 com.google.android.gm
    .\adb.exe shell pm uninstall --user 0 com.google.android.googlequicksearchbox
    .\adb.exe shell pm uninstall --user 0 com.google.android.gsf
    .\adb.exe shell pm uninstall --user 0 com.google.android.marvin.talkback
    .\adb.exe shell pm uninstall --user 0 com.google.android.syncadapters.contacts
    .\adb.exe shell pm uninstall --user 0 com.google.android.tts
    .\adb.exe shell pm uninstall --user 0 com.google.android.youtube
    .\adb.exe shell pm uninstall --user 0 com.mi.android.globalminusscreen
    .\adb.exe shell pm uninstall --user 0 com.mi.globalbrowser
    .\adb.exe shell pm uninstall --user 0 com.milink.service
    .\adb.exe shell pm uninstall --user 0 com.mipay.wallet.id
    .\adb.exe shell pm uninstall --user 0 com.mipay.wallet.in
    .\adb.exe shell pm uninstall --user 0 com.miui.analytics
    #.\adb.exe shell pm uninstall --user 0 com.miui.android.fashiongallery
    .\adb.exe shell pm uninstall --user 0 com.miui.audiomonitor
    .\adb.exe shell pm uninstall --user 0 com.miui.backup
    .\adb.exe shell pm uninstall --user 0 com.miui.bugreport
    .\adb.exe shell pm uninstall --user 0 com.miui.cloudbackup
    .\adb.exe shell pm uninstall --user 0 com.miui.cloudservice
    .\adb.exe shell pm uninstall --user 0 com.miui.cloudservice.sysbase
    .\adb.exe shell pm uninstall --user 0 com.miui.fm
    .\adb.exe shell pm uninstall --user 0 com.miui.fmservice
    .\adb.exe shell pm uninstall --user 0 com.miui.micloudsync
    .\adb.exe shell pm uninstall --user 0 com.miui.miservice
    .\adb.exe shell pm uninstall --user 0 com.miui.mishare.connectivity
    .\adb.exe shell pm uninstall --user 0 com.miui.miwallpaper
    .\adb.exe shell pm uninstall --user 0 com.miui.notes
    .\adb.exe shell pm uninstall --user 0 com.miui.phrases
    .\adb.exe shell pm uninstall --user 0 com.miui.player
    .\adb.exe shell pm uninstall --user 0 com.miui.screenrecorder
    .\adb.exe shell pm uninstall --user 0 com.miui.securitycenter
    .\adb.exe shell pm uninstall --user 0 com.miui.touchassistant
    .\adb.exe shell pm uninstall --user 0 com.miui.videoplayer
    .\adb.exe shell pm uninstall --user 0 com.miui.weather2
    .\adb.exe shell pm uninstall --user 0 com.miui.yellowpage
    .\adb.exe shell pm uninstall --user 0 com.qualcomm.location
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.account
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.calendar
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.discover
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.finddevice
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.glgm
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.joyose
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.location.fused
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.mi_connect_service
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.midrop
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.mipicks
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.mirecycle
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.payment
}

function rn6 {
    .\adb.exe shell pm uninstall --user 0 com.android.hotwordenrollment.okgocom.android.browser
    .\adb.exe shell pm uninstall --user 0 com.android.chrome
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.docs
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.maps
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.photos
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.tachyon
    .\adb.exe shell pm uninstall --user 0 com.google.android.apps.wellbeing
    .\adb.exe shell pm uninstall --user 0 com.google.android.feedback
    .\adb.exe shell pm uninstall --user 0 com.google.android.gm
    .\adb.exe shell pm uninstall --user 0 com.google.android.gms
    .\adb.exe shell pm uninstall --user 0 com.google.android.gms.location.history
    .\adb.exe shell pm uninstall --user 0 com.google.android.googlequicksearchbox
    #.\adb.exe shell pm uninstall --user 0 com.google.android.inputmethod.latin
    .\adb.exe shell pm uninstall --user 0 com.google.android.marvin.talkback
    .\adb.exe shell pm uninstall --user 0 com.google.android.music
    .\adb.exe shell pm uninstall --user 0 com.android.bips
    .\adb.exe shell pm uninstall --user 0 com.mi.globalbrowser
    .\adb.exe shell pm uninstall --user 0 com.android.bookmarkprovider
    .\adb.exe shell pm uninstall --user 0 com.google.android.printservice.recommendation
    .\adb.exe shell pm uninstall --user 0 com.android.calendar
    .\adb.exe shell pm uninstall --user 0 com.google.android.syncadapters.calendar
    .\adb.exe shell pm uninstall --user 0 com.google.android.tts
    .\adb.exe shell pm uninstall --user 0 com.google.android.videos
    .\adb.exe shell pm uninstall --user 0 com.google.android.youtube
    .\adb.exe shell pm uninstall --user 0 com.google.ar.lens
    .\adb.exe shell pm uninstall --user 0 com.android.wallpaper.livepicker
    .\adb.exe shell pm uninstall --user 0 com.android.printspooler
    .\adb.exe shell pm uninstall --user 0 com.android.egg
    .\adb.exe shell pm uninstall --user 0 com.android.emergency
    .\adb.exe shell pm uninstall --user 0 com.miui.msa.global
    .\adb.exe shell pm uninstall --user 0 com.mfashiongallery.emag
    .\adb.exe shell pm uninstall --user 0 com.mi.android.globalFileexplorer
    .\adb.exe shell pm uninstall --user 0 com.mi.globalTrendNews
    .\adb.exe shell pm uninstall --user 0 com.mi.health
    .\adb.exe shell pm uninstall --user 0 com.mipay.wallet.id
    .\adb.exe shell pm uninstall --user 0 com.mipay.wallet.in
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.payment
    .\adb.exe shell pm uninstall --user 0 com.miui.nextpay
    .\adb.exe shell pm uninstall --user 0 com.miui.analytics
    #.\adb.exe shell pm uninstall --user 0 com.miui.android.fashiongallery
    .\adb.exe shell pm uninstall --user 0 com.miui.aod
    .\adb.exe shell pm uninstall --user 0 com.miui.weather2
    .\adb.exe shell pm uninstall --user 0 com.miui.backup
    .\adb.exe shell pm uninstall --user 0 com.miui.bugreport
    .\adb.exe shell pm uninstall --user 0 com.miui.calculator
    .\adb.exe shell pm uninstall --user 0 com.miui.cleanmaster
    .\adb.exe shell pm uninstall --user 0 com.miui.cloudbackup
    .\adb.exe shell pm uninstall --user 0 com.miui.cloudservice
    .\adb.exe shell pm uninstall --user 0 com.miui.cloudservice.sysbase
    .\adb.exe shell pm uninstall --user 0 com.miui.micloudsync
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.micloud.sdk
    .\adb.exe shell pm uninstall --user 0 com.miui.compass
    .\adb.exe shell pm uninstall --user 0 com.miui.contentcatcher
    .\adb.exe shell pm uninstall --user 0 com.miui.extraphoto
    .\adb.exe shell pm uninstall --user 0 com.miui.fm
    .\adb.exe shell pm uninstall --user 0 com.miui.fmservice
    .\adb.exe shell pm uninstall --user 0 com.miui.freeform
    .\adb.exe shell pm uninstall --user 0 com.miui.gallery
    .\adb.exe shell pm uninstall --user 0 com.miui.greenguard
    .\adb.exe shell pm uninstall --user 0 com.miui.huanji
    .\adb.exe shell pm uninstall --user 0 com.miui.hybrid
    .\adb.exe shell pm uninstall --user 0 com.miui.hybrid.accessory
    .\adb.exe shell pm uninstall --user 0 com.miui.miservice
    .\adb.exe shell pm uninstall --user 0 com.miui.mishare.connectivity
    .\adb.exe shell pm uninstall --user 0 com.miui.misound
    .\adb.exe shell pm uninstall --user 0 com.miui.miwallpaper
    .\adb.exe shell pm uninstall --user 0 com.miui.miwallpaper.earth
    .\adb.exe shell pm uninstall --user 0 com.miui.miwallpaper.mars
    .\adb.exe shell pm uninstall --user 0 com.miui.newmidrive
    .\adb.exe shell pm uninstall --user 0 com.miui.gallery
    .\adb.exe shell pm uninstall --user 0 com.miui.notes
    .\adb.exe shell pm uninstall --user 0 com.miui.phrase
    .\adb.exe shell pm uninstall --user 0 com.miui.player
    .\adb.exe shell pm uninstall --user 0 com.miui.qr
    .\adb.exe shell pm uninstall --user 0 com.miui.screenrecorder
    .\adb.exe shell pm uninstall --user 0 com.miui.smsextra
    .\adb.exe shell pm uninstall --user 0 com.miui.touchassistant
    .\adb.exe shell pm uninstall --user 0 com.miui.translation.kingsoft
    .\adb.exe shell pm uninstall --user 0 com.miui.userguide
    .\adb.exe shell pm uninstall --user 0 com.miui.videoplayer
    .\adb.exe shell pm uninstall --user 0 com.miui.weather2
    .\adb.exe shell pm uninstall --user 0 com.miui.yellowpage
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.calendar
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.discover
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.glgm
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.joyose
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.location.fused
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.mi_connect_service
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.midrop
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.mipicks
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.miplay_client
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.mircs
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.scanner
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.xmsf
    .\adb.exe shell pm uninstall --user 0 com.xiaomi.xmsfkeeper
    .\adb.exe shell pm uninstall --user 0 com.facebook.katana
    .\adb.exe shell pm uninstall --user 0 com.facebook.appmanager
    .\adb.exe shell pm uninstall --user 0 com.facebook.services
    .\adb.exe shell pm uninstall --user 0 com.facebook.system
    .\adb.exe shell pm uninstall --user 0 com.caf.fmradio
    .\adb.exe shell pm uninstall --user 0 com.duokan.phone.remotecontroller
    .\adb.exe shell pm uninstall --user 0 in.amazon.mShop.android.shopping
    .\adb.exe shell pm uninstall --user 0 com.netflix.partner.activation
    .\adb.exe shell pm uninstall --user 0 com.netflix.mediaclient
    .\adb.exe shell pm uninstall --user 0 com.opera.app.news
    .\adb.exe shell pm uninstall --user 0 com.opera.branding
    .\adb.exe shell pm uninstall --user 0 com.opera.branding.news
    
    Set-Location ..
}
